# Generated by Django 5.1.3 on 2024-11-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
            ],
        ),
    ]
