# Generated by Django 5.1.3 on 2024-11-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiondata',
            old_name='rainfall',
            new_name='co2_emissions',
        ),
        migrations.RemoveField(
            model_name='regiondata',
            name='region_name',
        ),
    ]
