# Generated by Django 5.1.3 on 2024-11-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0002_rename_rainfall_regiondata_co2_emissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiondata',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
